name: taskify
description: A new Flutter project.

publish_to: "none"

version: 1.0.3+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  appflowy_board: ^0.0.9
  flutter_riverpod: ^2.1.3
  collection: ^1.16.0
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11
  cloud_firestore: ^4.3.1
  json_annotation: ^4.8.0
  hexcolor: ^3.0.1
  stateful_props: ^1.2.0+1
  flex_color_scheme: ^6.1.2
  duration: ^3.0.12
  go_router: ^6.0.9
  shared_preferences: ^2.0.17
  flutter_speed_dial: ^6.2.0
  flex_color_picker: ^3.0.2
  path_provider: ^2.0.12
  share_plus: ^6.3.1
  csv: ^5.0.1
  intl: ^0.18.0
  file_picker: ^5.2.5
  universal_io: ^2.2.0
  permission_handler: ^10.2.0
  file_selector: ^0.9.2+3
  universal_html: ^2.0.9
  freezed_annotation: ^2.2.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  icons_launcher: ^2.1.0

flutter:
  uses-material-design: true
